import type { Product } from '@/types/product';

/**
 * Mock products for when backend is not available (e.g. VITE_API_URL not set).
 * Mínimo 20 opções para testes e demonstração.
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    descricao: 'Notebook Ultra Slim 15"',
    codigo: 'ELEC-NB001',
    valorUnitario: 3299.9,
    unidade: 'UN',
    ncm: '84713012',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-2',
    descricao: 'Mouse sem fio ergonômico',
    codigo: 'ELEC-MOU02',
    valorUnitario: 89.9,
    unidade: 'UN',
    ncm: '85171210',
    cst: '00',
    cfop: '5102',
    ativo: false,
  },
  {
    id: 'mock-3',
    descricao: 'Teclado mecânico RGB',
    codigo: 'ELEC-TEC03',
    valorUnitario: 349.0,
    unidade: 'UN',
    ncm: '84716060',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-4',
    descricao: 'Camiseta básica algodão',
    codigo: 'VEST-CAM04',
    valorUnitario: 49.9,
    unidade: 'UN',
    ncm: '61091000',
    cst: '00',
    cfop: '5102',
    ativo: false,
  },
  {
    id: 'mock-5',
    descricao: 'Calça jeans slim',
    codigo: 'VEST-CAL05',
    valorUnitario: 159.9,
    unidade: 'UN',
    ncm: '62046200',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-6',
    descricao: 'Tênis esportivo corrida',
    codigo: 'VEST-TEN06',
    valorUnitario: 279.9,
    unidade: 'UN',
    ncm: '64041100',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-7',
    descricao: 'Café em grãos 500g',
    codigo: 'ALIM-CAF07',
    valorUnitario: 34.9,
    unidade: 'UN',
    ncm: '09012100',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-8',
    descricao: 'Chocolate ao leite 200g',
    codigo: 'ALIM-CHO08',
    valorUnitario: 18.5,
    unidade: 'UN',
    ncm: '18063200',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-9',
    descricao: 'Água mineral 1,5L pack 12',
    codigo: 'ALIM-AGU09',
    valorUnitario: 15.9,
    unidade: 'CX',
    ncm: '22011000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-10',
    descricao: 'Fone Bluetooth over-ear',
    codigo: 'ELEC-FON10',
    valorUnitario: 229.0,
    unidade: 'UN',
    ncm: '85183000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-11',
    descricao: 'Mochila executiva 15"',
    codigo: 'ACE-MOC11',
    valorUnitario: 189.9,
    unidade: 'UN',
    ncm: '42021290',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-12',
    descricao: 'Caderno universitário 200 fls',
    codigo: 'PAP-CAD12',
    valorUnitario: 24.9,
    unidade: 'UN',
    ncm: '48201000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-13',
    descricao: 'Caneta esferográfica pack 12',
    codigo: 'PAP-CAN13',
    valorUnitario: 12.9,
    unidade: 'PC',
    ncm: '96081000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-14',
    descricao: 'Garrafa térmica 500ml',
    codigo: 'ACE-GAR14',
    valorUnitario: 59.9,
    unidade: 'UN',
    ncm: '96170010',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-15',
    descricao: 'Relógio smartwatch esportivo',
    codigo: 'ELEC-REL15',
    valorUnitario: 449.0,
    unidade: 'UN',
    ncm: '91021200',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-16',
    descricao: 'Carregador portátil 10000mAh',
    codigo: 'ELEC-CAR16',
    valorUnitario: 79.9,
    unidade: 'UN',
    ncm: '85076000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-17',
    descricao: 'Sabonete líquido 250ml',
    codigo: 'HIG-SAB17',
    valorUnitario: 14.9,
    unidade: 'UN',
    ncm: '34013000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-18',
    descricao: 'Shampoo anticaspa 400ml',
    codigo: 'HIG-SHA18',
    valorUnitario: 32.9,
    unidade: 'UN',
    ncm: '33051000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-19',
    descricao: 'Luminária LED mesa',
    codigo: 'DEC-LUM19',
    valorUnitario: 119.9,
    unidade: 'UN',
    ncm: '94052000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-20',
    descricao: 'Produto descontinuado (inativo)',
    codigo: 'OUT-DES20',
    valorUnitario: 9.9,
    unidade: 'UN',
    ncm: '99999999',
    cst: '00',
    cfop: '5102',
    ativo: false,
  },
  {
    id: 'mock-21',
    descricao: 'Organizador de gaveta 5 peças',
    codigo: 'DEC-ORG21',
    valorUnitario: 44.9,
    unidade: 'UN',
    ncm: '39241000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
  {
    id: 'mock-22',
    descricao: 'Kit canetas coloridas 24 cores',
    codigo: 'PAP-KIT22',
    valorUnitario: 29.9,
    unidade: 'UN',
    ncm: '96081000',
    cst: '00',
    cfop: '5102',
    ativo: true,
  },
];

let mockStore = [...MOCK_PRODUCTS];

export function getMockProducts(): Product[] {
  return [...mockStore];
}

export function updateMockProduct(id: string, payload: Partial<Product>): Product | null {
  const index = mockStore.findIndex((p) => p.id === id);
  if (index === -1) return null;
  mockStore[index] = { ...mockStore[index], ...payload };
  return mockStore[index];
}
